# Generated by Django 5.1.1 on 2024-09-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ipoinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('price_band', models.CharField(max_length=100)),
                ('open', models.DateField()),
                ('close', models.DateField()),
                ('issue_size', models.IntegerField()),
                ('issue_type', models.CharField(max_length=50, null=True)),
                ('listing_date', models.DateField()),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Coming', 'Coming'), ('New Listed', 'New Listed')], default='Ongoing', max_length=50)),
                ('ipo_price', models.CharField(max_length=100)),
                ('listing_price', models.CharField(max_length=100)),
                ('listing_gain', models.CharField(max_length=100)),
                ('cmp', models.CharField(max_length=100)),
                ('current_return', models.CharField(max_length=100)),
                ('rhp', models.CharField(max_length=100)),
                ('drhp', models.CharField(max_length=100)),
                ('action', models.BinaryField()),
            ],
        ),
    ]
